name: rec3d_pkg
root: ~/
startup_window: planner
windows:
  - bash:
      layout: tiled
      panes:
        -
  - roscore:
      layout: tiled
      panes:
        - roscore
  - statue:
      layout: tiled
      panes:
        - sleep 2;roslaunch rec3d statue.launch
  - uavs:
      layout: tiled
      panes:
        - sleep 2; roslaunch rec3d spawn_uav.launch mav_name:=pelican y:=0.5
        # - sleep 2; roslaunch rec3d spawn_uav.launch mav_name:=hummingbird y:=-0.5
  - planner:
      layout: tiled
      panes:
        # - sleep 10; rosrun rec3d behavior_tree_node /home/nicolas/catkin_ccmslam/src/rec3d/config/behavior_tree.xml
        - sleep 10; rosrun rec3d main_tree_node /home/nicolas/catkin_ccmslam/src/rec3d/config/behavior_tree.xml


#   - orb_slam:
#       layout: tiled
#       panes:
#         - sleep 3; roslaunch rec3d orb_slam_mono.launch
#         - sleep 4; rosrun image_view image_view image:=/orb_slam2_mono/debug_image
#   - republish:
#       layout: tiled
#       panes:
#         - sleep 4; rosrun image_transport republish raw in:=/pelican/camera_monocular/image_raw raw out:=/camera/image_raw
#   - rviz:
#       layout: tiled
#       panes:
#         - sleep 1;rviz
#   - bag:
#       layout: tiled
#       panes:
#         - sleep 5; rosbag play /home/nicolas/Desktop/bag/test_bag.bag
#   - camera:
#        layout: tiled
#        panes:
#         - sleep 4; rosrun image_view image_view image:=/camera/image_raw