start_position:
  x: 5.0
  y: 0.5
  z: 0.5
  heading: 0.0

topics:
  odometry: "/hummingbird/odometry_sensor1/pose"
  camera: "/hummingbird/camera_monocular/image_raw"
  pose: "/hummingbird/command/pose"

uav_name: "hummingbird"
